# Generated by Django 6.0.5 on 2026-06-01 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='custo_total_financeiro',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Qtd x Preço no momento', max_digits=12),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Quem realizou', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produto',
            name='cliente_reserva_id',
            field=models.IntegerField(blank=True, help_text='ID do Cliente se o item estiver reservado', null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor_id',
            field=models.IntegerField(blank=True, help_text='ID do parceiro do Módulo de Fornecedores', null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='localizacao_deposito',
            field=models.CharField(blank=True, help_text='Ex: Corredor A, Prateleira 3', max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='status_reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoria'),
        ),
    ]
